5/29-week6 Commit
p83129/taipei-day-trip-website pull request #10
Opened 2021-05-29 09:59 UTC by p83129

老師你好~
我是郁庭，來繳交第六週作業，多多指教 :)

http://54.178.112.226:3000/

2021-05-29 19:52 UTC, cwpeng commented
我看的時候資料庫應該是斷掉了哦，麻煩恢復後再和我說 :)

2021-05-30 00:47 UTC, p83129 commented
> 我看的時候資料庫應該是斷掉了哦，以後會遇到麻煩和我說：）

老師我又重新連上了，請再幫我是一次~~

2021-05-30 01:33 UTC, cwpeng requested changes
雖然付款是可以運作的，但你的 POST /api/orders 接收資料的方式和接受資料的內容都和 API 定義的相距蠻大，我們需要紀錄使用者輸入各種資訊，並且使用 JSON 的格式來處理哦。

請再把 API 細節處理一下跟我說 ~

2021-05-30 04:43 UTC, p83129 commented
> 我付款是可以服務的，但你的 POST /api/orders 接收數據的方式和接受數據的內容都和 API 定義的相距很大，我們需要記錄用戶輸入各種信息，並且使用 JSON 的格式來哦處理。
> 
> 請再把API細節處理一下我的說說~

API部分 我改好了~ 請再幫我試試看  謝謝~~

2021-05-30 17:25 UTC, cwpeng requested changes
付款的部份沒問題，但使用者登入的部分不太穩定，因為你使用 <form> 可能會在你的 API 呼叫完成前就重新載入網頁，導致登入的動作沒有真的發生，請把這點修好，日後也要多注意使用 AJAX 和 <form> 之間的衝突。

請調整好這部分再和我說哦 ~

2021-05-31 01:35 UTC, p83129 commented
> form 可能會在你的 API 呼叫完成前就重新載入網頁，

老師我已經修改好問題了~
一直以為是我的電腦有問題XDD  找朋友幫忙測試也都回覆給我的是OK的，原來是 AJAX 和 form 使用上的會有衝突阿
感謝老師~~

2021-05-31 01:51 UTC, cwpeng requested changes
好哦，看起來是改善了 :)

不過我順便發現了，你的使用者登入的 API 和 orders 有一樣的問題，傳遞資訊的方式要按照 API 規格使用 JSON 的格式來處理，使用者密碼不適合放在 Query String 中傳遞。就再麻煩你改善這點嘍，之後也多多注意這些細節，對不同的前後端資料的傳遞方式都有些掌握是重要的事情 ~

2021-05-31 08:56 UTC, p83129 commented
> 好哦，看起來是改善了 :)
> 
> 不過我順便發現了，你的使用者登入的 API 和 orders 有一樣的問題，傳遞資訊的方式要按照 API 規格使用 JSON 的格式來處理，使用者密碼不適合放在 Query String 中傳遞。就再麻煩你改善這點嘍，之後也多多注意這些細節，對不同的前後端資料的傳遞方式都有些掌握是重要的事情 ~

老師我這部分也改好了~  請再幫我查看 謝謝你~

2021-05-31 22:18 UTC, cwpeng approved these changes
好哦，這樣就可以，辛苦了 :)

2021-06-01 00:54 UTC, merged