Develop
p83129/taipei-day-trip-website pull request #7
Opened 2021-05-07 05:53 UTC by p83129

我是郁庭~ 改好畫面的問題，請老師在幫忙查看 謝謝~~

http://54.178.112.226:3000

http://54.178.112.226:3000/attraction/220

2021-05-07 06:01 UTC, cwpeng requested changes
有好很多，不過手機版的部份，請你試試看 360px 寬度的螢幕，你的圖片輪播的區塊會超出版面，這點請再修正哦。

修正完直接在同一個 Pull Request 右上角發新的 Review 請求給我就可以了，不用重開新的 Pull Request 哦，這樣可以方便我們追蹤狀況 ~

2021-05-07 06:46 UTC, p83129 reviewed
老師我已經設定為360px請在幫我看一下 謝謝~

2021-05-07 08:36 UTC, cwpeng commented
可是中間的平板版面反而超出螢幕了，我們要同時考慮每個狀況哦，改完之後要全部都測試過 ~
![54 178 112 226_3000_attraction_220 (1)](https://user-images.githubusercontent.com/6104683/117422577-56995300-af52-11eb-9c11-f425242ff52b.png)

2021-05-09 12:40 UTC, p83129 reviewed
老師我修改好畫面了~ 請再幫忙查看 謝謝你~~

2021-05-09 14:05 UTC, cwpeng commented
好哦，這樣就可以了，有改善很多，但請重新發 Review Request 給我，我才能幫你 Approve

2021-05-10 05:16 UTC, p83129 commented
已重新發 Review Request 給你了~~

2021-05-10 07:18 UTC, cwpeng approved these changes
OK 哦，這樣就可以 :)

2021-05-10 07:40 UTC, merged