5/20-week5 Commit
p83129/taipei-day-trip-website pull request #9
Opened 2021-05-20 05:44 UTC by p83129

老師你好~ 我是郁庭
來繳交這次作業~~

http://54.178.112.226:3000/
http://54.178.112.226:3000/attraction/220
http://54.178.112.226:3000/booking

關於上次說的會員密碼 我也已經改好了 :)

2021-05-20 09:13 UTC, cwpeng commented
伺服器的資料庫連線可能斷了，重新啟動恢復後再和我說 ~

2021-05-20 12:24 UTC, p83129 commented
> 伺服器的資料庫連線可能斷了，重新啟動恢復後再和我說〜

已經重新啟動了 請老師在確認一下 謝謝~~

2021-05-20 18:01 UTC, cwpeng requested changes
我點進預定行程頁面會出錯誤，首頁和景點頁也無法點擊預定行程的按鈕，注意新使用者的 Session 狀況，你可以用無痕視窗模擬一個第一次到訪的使用者來測試，請參考以下截圖：
![未命名-4](https://user-images.githubusercontent.com/6104683/119026977-61cf9280-b9d8-11eb-8dff-1b4337c22cd5.png)

2021-05-21 02:47 UTC, p83129 commented
> 我點進預定行程頁面會出錯誤，首頁和景點頁面也無法點擊預定行程的按鈕，注意新用戶的Session狀態，你可以用無痕視窗模擬一個第一次到訪者的使用者來測試，請參考以下截圖：
> ![未命名-4](https://user-images.githubusercontent.com/6104683/119026977-61cf9280-b9d8-11eb-8dff-1b4337c22cd5.png)

老師我已經改好了~請在幫我查看一下 謝謝你~~

2021-05-21 07:42 UTC, cwpeng approved these changes
好哦，這樣就可以了 :)

2021-05-21 07:50 UTC, merged